### ISSUE TITLE
Integrating REST APIs within FASTEN.

### ISSUE THREAD

**Issue by michelescarlato** [fasten-project/LCV-CM#1]
@wzorgdrager, I am reaching out to ask how to integrate the REST APIs LCV exposes (containerizing a flask server) with the Maven Java Fasten architecture.

I am Looking forward to your instructions.

Thanks,
Michele

**Comment by wzorgdrager** [comment]
HI @michelescarlato, I can help of course. If I understand correctly, you have a Flask container that needs to be exposed to the outside world? Or will it only be internally used? Nevertheless, we need to:
1) Dockerize your app. Looking at your repo, this is already done? It is also important that the Docker image is published somewhere, either Docker Hub or GitHub Packages will do the trick. We use GitHub Packages for most deployments (see the main fasten repo). 
2) Create a Kubernetes deployment manifest.
3) Put it behind a Kubernetes service. For that, we also need to have a manifest.

Afterwards, it should be addressable by all other deployments in the cluster. For 2-3, you can find some examples in the [Kubernetes manifests repo](https://github.com/fasten-project/k8s-deployments): your manifests need to be similar to the `rest-api` ones.

If you want to have this service available outside our cluster, we need to expose it via our nginx setup on lima. This is something only @mir-am or I can do.

Let me know what you want and where you need help!

**Comment by michelescarlato** [comment]
Hi @wzorgdrager, thanks for your quick reply.

To answer your question, Thomas (@tmortagne) knows better than me how he wants to make the calls to the REST APIs provided by LCV.

For point `1`, yes, my app is already dockerized.
I also have a workflow that runs an action that builds the image and performs REST APIs tests with Newman (that uses Postman under the hood).

While I had experience with Docker Hub, I didn't have it with GitHub packages, and I am trying to understand better how to keep aligned with the other deployments.

I looked at the [docker-opal-plugin](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/docker-opal-plugin.yml), but I am not sure if I have to add the `Setup JDK 11 step`.

LCV doesn't need Java at all to run.

To help me on point `1`, could you please take a look at the [LCV.yml](https://github.com/fasten-project/LCV-CM/blob/develop/LCV.yml) that I am trying to write, and it is supposed to end up into the fasten [.github/workflows/](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/) directory?

Please consider that I am using the `DockerfileExternal` to build the LCV image. `Dockerfile` is used to build an image with REST APIs tests integrated, used by GitHub actions.

**Comment by tmortagne** [comment]
> To answer your question, Thomas (@tmortagne) knows better than me how he wants to make the calls to the REST APIs provided by LCV.

Only that I expect to have this license validation to be exposed as a new endpoint of the FASTEN REST API. The details of what need to be sent to this API and what I receive in return is up to you.

**Comment by proksch** [comment]
One important use case is that the license extractions also needs to work locally for the project on which the `mvn` command is actually being invoked... how is this being realized, when the plug-in runs on the server?

I did not yet understand the benefit of using a Docker container vs. providing a library.

**Comment by tmortagne** [comment]
> I did not yet understand the benefit of using a Docker container vs. providing a library.

None. I just proposed to Endocode to quickly expose the tool they already built for license validation as a REST API so that the Maven plugin start using it while they are working on a Java version which seems to be something that would take a long time from what I understood.

The short term plan on the Maven plugin side is to ask Maven for the package level license of each dependency and use that new service to validate them using that new REST API. Later when a license extraction tool is available this will just be a fallback in case no license can be found for a specific callable.

**Comment by wzorgdrager** [comment]
> Hi @wzorgdrager, thanks for your quick reply.
> 
> To answer your question, Thomas (@tmortagne) knows better than me how he wants to make the calls to the REST APIs provided by LCV.
> 
> For point `1`, yes, my app is already dockerized.
> I also have a workflow that runs an action that builds the image and performs REST APIs tests with Newman (that uses Postman under the hood).
> 
> While I had experience with Docker Hub, I didn't have it with GitHub packages, and I am trying to understand better how to keep aligned with the other deployments.
> 
> I looked at the [docker-opal-plugin](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/docker-opal-plugin.yml), but I am not sure if I have to add the `Setup JDK 11 step`.
> 
> LCV doesn't need Java at all to run.
> 
> To help me on point `1`, could you please take a look at the [LCV.yml](https://github.com/fasten-project/LCV-CM/blob/develop/LCV.yml) that I am trying to write, and it is supposed to end up into the fasten [.github/workflows/](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/) directory?
> 
> Please consider that I am using the `DockerfileExternal` to build the LCV image. `Dockerfile` is used to build an image with REST APIs tests integrated, used by GitHub actions.

You can indeed skip the `Setup JDK 11` step. Instead, you need to make sure a proper Docker image is built in this workflow and then do something similar as step `Log into registry` and `Push image`. I see this already what you did in your `yml` file. Putting it in `.github/workflows` will make it run on each push. I would suggest trying it and see if it works. 

Also, in the end, I think it would be easier to only have this Flask app running internally (and not directly expose it to the outside world). We can use the 'other' REST-API as a proxy for this Flask instance. I.e. you can call the default REST API, which internally queries this license REST API.

**Comment by proksch** [comment]
IIRC, we have an nginx running in front of the REST API, don't we? For quick results, it should be straight forward to configure a custom path that is then routed to this flask container. Ultimately, however, I would say that having a library and a realization of this checking in the Spring server (like all other results) would make the most sense.

**Comment by michelescarlato** [comment]
> > Hi @wzorgdrager, thanks for your quick reply.
> > To answer your question, Thomas (@tmortagne) knows better than me how he wants to make the calls to the REST APIs provided by LCV.
> > For point `1`, yes, my app is already dockerized.
> > I also have a workflow that runs an action that builds the image and performs REST APIs tests with Newman (that uses Postman under the hood).
> > While I had experience with Docker Hub, I didn't have it with GitHub packages, and I am trying to understand better how to keep aligned with the other deployments.
> > I looked at the [docker-opal-plugin](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/docker-opal-plugin.yml), but I am not sure if I have to add the `Setup JDK 11 step`.
> > LCV doesn't need Java at all to run.
> > To help me on point `1`, could you please take a look at the [LCV.yml](https://github.com/fasten-project/LCV-CM/blob/develop/LCV.yml) that I am trying to write, and it is supposed to end up into the fasten [.github/workflows/](https://github.com/fasten-project/fasten/blob/develop/.github/workflows/) directory?
> > Please consider that I am using the `DockerfileExternal` to build the LCV image. `Dockerfile` is used to build an image with REST APIs tests integrated, used by GitHub actions.
> 
> You can indeed skip the `Setup JDK 11` step. Instead, you need to make sure a proper Docker image is built in this workflow and then do something similar as step `Log into registry` and `Push image`. I see this already what you did in your `yml` file. Putting it in `.github/workflows` will make it run on each push. I would suggest trying it and see if it works.
> 
Hi, Wouter (@wzorgdrager), 
I put my `LCV.yml` file in `.github/workflows` and the action terminates without errors.
I still have one main concern:
"How can I be sure that the image has really being published at `docker.pkg.github.com/fasten-project/lcv-cm/fasten.lcv.plugin` ?"

I tried:
`docker login docker.pkg.github.com`
... and received...

```
Username: michelescarlato
Password: 
WARNING! Your password will be stored unencrypted in /home/michelescarlato/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
```

But when I try:
`docker pull docker.pkg.github.com/fasten-project/lcv-cm/fasten.lcv.plugin`
.... I receive ...
`Using default tag: latest
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.`

Is there a way to double-check if the image has been pushed correctly?

Another concern is related to the warning. The first command has been run on my local machine, to try to pull the image (to double-check), but the same warning appeared also in the GitHub workflows, in the `Log into registry` step.
Could you suggest a way to prevent it?
Should I have to use a token?
Where do I have to set the token configuration?

Thank you so much for your attention and participation.
Michele

**Comment by wzorgdrager** [comment]
@michelescarlato 
It seems to be working fine, you can see it here: https://github.com/fasten-project/LCV-CM/packages/838908 
To use it locally; see [this guide](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry). In short, you need to generate a token to get it working. 

I don't really understand why we have the warning in the workflow because we already use tokens there (not a password).

**Comment by michelescarlato** [comment]
> @michelescarlato
> It seems to be working fine, you can see it here: https://github.com/fasten-project/LCV-CM/packages/838908
> To use it locally; see [this guide](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry). In short, you need to generate a token to get it working.

@wzorgdrager
I created a token, and I am now able to pull the image.
When I am pulling it, I receive this warning:

```
WARNING: ⚠️ Failed to pull manifest by the resolved digest. This registry does not
	appear to conform to the distribution registry specification; falling back to
	pull by tag.  This fallback is DEPRECATED, and will be removed in a future
	release.  Please contact admins of https://docker.pkg.github.com. ⚠️
```
On Friday, I tried to understand where it comes from, but it is unclear to me.

Anyway, I can run the image locally.

> 
> I don't really understand why we have the warning in the workflow because we already use tokens there (not a password).

I am running the workflow in my repo `LCV-CM`. I didn't set the token there. Or the usage of tokens is set at the organizational level (at the `fasten-project` level)? 


Regarding steps 2 and 3 that you indicated to me, I tried to follow your suggestion:
 `For 2-3, you can find some examples in the Kubernetes manifests repo: your manifests need to be similar to the rest-api ones.`

I tried to adapt the three manifests in [k8s-manifests/](https://github.com/fasten-project/LCV-CM/tree/develop/k8s-manifests)  used by `rest-api`.
Could you please take a look at them?

I don't have an idea about how to set some parameters in configmaps. 

Thanks for the support provided so far,
Michele

**Comment by wzorgdrager** [comment]
@michelescarlato 

> I am running the workflow in my repo LCV-CM. I didn't set the token there. Or the usage of tokens is set at the organizational level (at the fasten-project level)?

I think the token is automatically available in GitHub workflows. Otherwise, we have configured it somewhere for the whole organization, I'm not entirely sure.

> When I am pulling it, I receive this warning:

As for the warning, I haven't seen that before. We probably have to look into that.

> Could you please take a look at them?

In general, the manifests look good to me! When they are final, could you also add them to the K8s deployment manifest repository?

As for the ConfigMaps, in your deployment manifest, you're currently not using it? Do you need any ConfigMaps at all? For example, a password for one of the databases?

**Comment by michelescarlato** [comment]
@wzorgdrager, sorry for the late reply, and thanks for your constant support.

> @michelescarlato
> 
> I think the token is automatically available in GitHub workflows. Otherwise, we have configured it somewhere for the whole organization. I'm not entirely sure.

ok, thanks for the explanation.

> As for the warning, I haven't seen that before. We probably have to look into that.

I agree with you. Please let me know if I can do something regarding it.

 
> In general, the manifests look good to me! When they are final, could you also add them to the K8s deployment manifest repository?

I created a branch called `lcv-restapi` and pushed them.
I am really sorry, but honestly, I don't know how to test if they are currently functioning.

 
> As for the ConfigMaps, in your deployment manifest, you're currently not using it? Do you need any ConfigMaps at all? For example, a password for one of the databases?
As you are correctly supposing, I am not using any password because I am do not have to access any database. 

Thanks again for your precious support.
Michele

**Comment by wzorgdrager** [comment]
@michelescarlato 

Do you already have access to the cluster? If so, do you also have access to our K8s cluster? Try `kubectl info` and see if it works. If not, we can arrange this and I will give you some pointers on how to deploy. At this point, I think we should just try if it works and then fix the manifests if they do not. 

Btw, I think you can drop the ConfigMaps if you don't need any of those DB credentials.

**Comment by michelescarlato** [comment]
@wzorgdrager 
Thanks for your very active and constant support.

Sadly still, I don't have access to the cluster.

**Comment by michelescarlato** [comment]
@wzorgdrager, sorry for the silly question, but are you the right person to activate a user for the two environments you mentioned (the `cluster` and your `k8s cluster`)?
Probably I wrongly assumed that (by reading other issues).

In this case, I apologize, and I would ask you who the person in charge of it is.
I really appreciate any help you can provide.
Michele

**Comment by wzorgdrager** [comment]
@michelescarlato Don't worry, I can help you. In general, @mir-am took over most of the cluster duties since I'm working on my master thesis but I can definitely help. Please send me an email with a public key + a username you prefer. I will setup, an account for you on the cluster then.

**Comment by michelescarlato** [comment]
> @michelescarlato Don't worry, I can help you.

thank you so much @wzorgdrager !

> In general, @mir-am took over most of the cluster duties since I'm working on my master thesis but I can definitely help. 

I am sure you are going to write a great thesis! 

> Please send me an email with a public key + a username you prefer. I will setup, an account for you on the cluster then.

email: `michele.scarlato@gmail.com`

public key
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/ROrWvTLlXbFyCxx3b45tZCASOrOKupDz5xV/ZTUhMeDJkiaEvyie3loBNFADjblGh75OOP23f4VbjEV1GuSg3rwmep09rUmsAle2mIyMfoi01xf9gtIK5FkIPRNojsCnr5ADZh1NiQqllpd+CVcFbeqW3e0rMrckxq/hGD6X5XAMAJg0LltMBmumPW0hQf5RN4UW0pLHuVZjsG38GMsU7gplfSmmR9yZPXggyeuFrGF/pRThEh3cYEghRrPY/9anP898yS8Od8jXKsbvsWv3LHn9/g6AvyDp56hh7jwR7IW72cXEn751wZYdhRX39RVqy7ROwdM2N94YNX8aOZUfJbasrTB291dhIK0xb1F4xjvkXZkK1i3oQiFybixiB8ig+SZ9Yr1WSGyabVczwtraS0Gj1ZqCBLTdeEHHVMqbktZU1HC6Y13+wDPndFH4MxmSfycnHPX0dhw1MEcVSnT1GaQejwvwzT83XamHniVKMKLAAuseCZxdMxEUCeF73z0= michelescarlato@krang`

user: `michelescarlato`



Thanks for your help!

**Comment by michelescarlato** [comment]
> @michelescarlato
> 
> Do you already have access to the cluster? If so, do you also have access to our K8s cluster? Try `kubectl info` and see if it works. If not, we can arrange this and I will give you some pointers on how to deploy. At this point, I think we should just try if it works and then fix the manifests if they do not.

@wzorgdrager, thanks for your help!

Yes, now I have access to the K8s cluster. 
`kubectl get nodes` runs smoothly.
`kubectl info` no (the command doesn't exist ;) ).

How do you suggest I proceed?
Clone the repo with:
`git clone git@github.com:fasten-project/k8s-deployments.git`

checkout my branch 
` git checkout lcv-restapi`

and run:

`kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-deployment.yaml` 
and
`kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-service.yaml` 

Are these the main steps? Do you suggest doing something else?

Thank you so much for your attention and participation.
Michele

**Comment by wzorgdrager** [comment]
@michelescarlato 
No, I think this is a good approach. Just try it like that, and see if it works.

**Comment by michelescarlato** [comment]
Ok. The service seems up.
```
wget http://192.168.60.116:3251/APIEndpoints
--2021-06-24 10:24:48--  http://192.168.60.116:3251/APIEndpoints
Connecting to 192.168.60.116:3251... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3132 (3.1K) [text/html]
Saving to: ‘APIEndpoints’

APIEndpoints        100%[===================>]   3.06K  --.-KB/s    in 0s      

2021-06-24 10:24:48 (286 MB/s) - ‘APIEndpoints’ saved [3132/3132]
```
I have one question/doubt, to reach LCV-container I should use the IP address `192.168.60.116` , how to make it accessible from the external world? And how to make it accessible for @tmortagne?

With an `nginx` I guess, as Sebastian suggested?

**Comment by wzorgdrager** [comment]
Internally it should be accessible from something like `lcv-restapi-access:3251`. We indeed need nginx to expose it to the outside world, I hope @mir-am can help with that. He also did some nginx updates/fixes to the cluster lately. I think we need to have setup some sort of proxy inside nginx to a port on lima (similarly as we did for the restAPI). @mir-am any thoughts here?

**Comment by michelescarlato** [comment]
> Internally, it should be accessible from something like `lcv-restapi-access:3251`. 

I cannot reach it nor with `wget lcv-restapi-access:3251` neither with `wget lcv-fasten-restapi:3251`. Any suggestion to debug this?

`wget lcv-restapi-access:3251`
`--2021-06-24 10:47:57--  http://lcv-restapi-access:3251/
Resolving lcv-restapi-access (lcv-restapi-access)... failed: Name or service not known.
wget: unable to resolve host address ‘lcv-restapi-access’`
same error:
`wget lcv-fasten-restapi:3251`
`--2021-06-24 10:47:45--  http://lcv-fasten-restapi:3251/
Resolving lcv-fasten-restapi (lcv-fasten-restapi)... failed: Name or service not known.
wget: unable to resolve host address ‘lcv-fasten-restapi’`


Here is the [deployment](https://github.com/fasten-project/k8s-deployments/blob/lcv-restapi/fasten/lcv-rest-api/lcv-restapi-deployment.yaml) yaml file and here the [service](https://github.com/fasten-project/k8s-deployments/blob/lcv-restapi/fasten/lcv-rest-api/lcv-restapi-service.yaml) one.

Do you see any incongruence in these files?

**Comment by wzorgdrager** [comment]
@michelescarlato Internally I mean from inside the K8s cluster. That is, in one of the pods/containers. Did you try that? You could try to start a dummy pod and execute a command inside this pod to see if this works (there are quite some examples on the internet).

**Comment by michelescarlato** [comment]
Ok, now I got it, sorry.

I will give it a try and let you know.
I wait for @mir-am instructions regarding the access to the docker container for the maven plugin (required by @tmortagne ).

So far, thank you very much for your help @wzorgdrager!

**Comment by mir-am** [comment]
> Internally it should be accessible from something like `lcv-restapi-access:3251`. We indeed need nginx to expose it to the outside world, I hope @mir-am can help with that. He also did some nginx updates/fixes to the cluster lately. I think we need to have setup some sort of proxy inside nginx to a port on lima (similarly as we did for the restAPI). @mir-am any thoughts here?

@wzorgdrager @michelescarlato
Sorry, I just saw the discussion here.
I will check out the deployment file and give instructions to expose the REST API.

**Comment by michelescarlato** [comment]
@mir-am Dear Amir, thanks a lot for your effort. The deployment on Lima seems quite good.

I have two important questions:

1. I am currently heavily refactoring the LCVServer to provide @tmortagne Thomas with a different approach, trying to solve his issues related to the missing `SPDX-ids` in `pom.xml` files. I am substantially providing a lite version of LCV, focusing on the Maven use case (currently hosted in another repo but soon integrated here).  
I have no idea how to deploy new docker image versions. I don't have enough privileges, I guess. Could you please clarify this point?

2. LCV is also offering HTML endpoints (mostly for debugging purposes) that, as far as I could observe, all of them are now providing `404 errors`. Do you have any idea how I can troubleshoot this? I would probably need to access the shell where the flask (LCVServer) is running. I suppose that the HTML endpoints call the 3251 port, which now becomes 443 (which I am using for the other REST APIs methods). Probably if I modify this value, I can bring it up again.

**Comment by mir-am** [comment]
> Can you run the `kubectl get deployments -n fasten` command successfully on servers?

Yes I can! :)

> Could you send me an example to reproduce the error?
> Also, you can use a shell inside your pod. There is a command for that. 

For example, using an endpoint such as `Compatibility SPDX Verifier API`, I got back 404.
Here two screenshots are showing it.
![https:--lima ewi tudelft nl-lcv-APIEndpoints - Google Chrome_052](https://user-images.githubusercontent.com/10910590/124685459-4975f180-df0c-11eb-9afa-01d76798695e.png)
![404 Not Found - Google Chrome_053](https://user-images.githubusercontent.com/10910590/124685467-4c70e200-df0c-11eb-9e71-462e90a9dab3.png)


I could get in using:
`kubectl -n fasten exec --stdin --tty lcv-fasten-restapi-77bdc76dfd-dgrrq -- /bin/bash`

And have access to a shell.

To troubleshoot, I should uncomment a line storing logs on file (usually, I was debugging on the flask shell, which I cannot access).

I think I have almost all the information for the debugging.
One only last question, do you know how I can deploy the last docker image created?
Unluckily I was using the tag `latest`, and I guess this would cause a problem with the docker image cached.

**Comment by mir-am** [comment]
> To troubleshoot, I should uncomment a line storing logs on file (usually, I was debugging on the flask shell, which I cannot access).
> 
> I think I have almost all the information for the debugging.
> One only last question, do you know how I can deploy the last docker image created?
> Unluckily I was using the tag `latest`, and I guess this would cause a problem with the docker image cached.

For debugging, you can also use `kubectl logs -f -n fastn pod-name` to see the pod's logs.
Each time you re-deploy LCV on K8s, it automatically pulls the latest image from GH packages. So you should re-deploy again.

**Comment by michelescarlato** [comment]
> > To troubleshoot, I should uncomment a line storing logs on file (usually, I debug the flask shell, which I cannot access).
> > I think I have almost all the information for the debugging.
> > One only last question, do you know how to deploy the last docker image created?
> > Unluckily, I was using the tag `latest`, and I guess this would cause a problem with the docker image cached.
> 
> For debugging, you can also use `kubectl logs -f -n fasten pod-name` to see the pod's logs.
As far as I see, the request never reaches the backend. Inside LCVServer.py, the HTML endpoints recall itself to 127.0.0.1:3251. 
A possible fix could try to substitute 3251 with 443 (in the case with the POST REST API endpoints if functioned) or using the IP address where the pod is running (but I guess it could change and it is not statically assigned).


![image](https://user-images.githubusercontent.com/10910590/124851669-f1a7bb00-dfdd-11eb-90f2-4a4c9c96275f.png)




> Each time you re-deploy LCV on K8s, it automatically pulls the latest image from GH packages. So you should re-deploy again.

I guess these two commands:

`kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-deployment.yaml`
and
`kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-service.yaml`

Am I correct?

**Comment by mir-am** [comment]
> I guess these two commands:
> 
> `kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-deployment.yaml`
> and
> `kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-service.yaml`
> 
> Am I correct?

Yes, use these two commands to re-deploy. However, you might need to delete your previous deployment first and then re-deploy. Check out our wiki [page](https://github.com/fasten-project/fasten/wiki/Managing-Kafka,-Docker-and-Kubernetes) for the list of K8s and Docker commands.

**Comment by michelescarlato** [comment]
Hi @mir-am Amir,

Sorry for the very late reply.
Today I tried to re-deploy a new image on K8s, but after redeploying, I still got the old image (it probably is cached and needs to be removed, but it seems that I don't have enough permissions).

I post here the commands used so far:

```
kubectl get deployments -n fasten
kubectl delete deployment -n fasten lcv-fasten-restapi
kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-deployment.yaml
kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-service.yaml
```
And when I am connecting to:
`https://lima.ewi.tudelft.nl/lcv/APIEndpoints`
I still got the old Endpoints page.

So I tried:

michelescarlato@monster:~$ `docker image ls`
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json: dial unix /var/run/docker.sock: connect: permission denied
`

Thank you in advance for your support,
Michele

**Comment by mir-am** [comment]
> Hi @mir-am Amir,
> 
> Sorry for the very late reply.
> Today I tried to re-deploy a new image on K8s, but after redeploying, I still got the old image (it probably is cached and needs to be removed, but it seems that I don't have enough permissions).
> 
> I post here the commands used so far:
> 
> ```
> kubectl get deployments -n fasten
> kubectl delete deployment -n fasten lcv-fasten-restapi
> kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-deployment.yaml
> kubectl apply -f k8s-deployments/fasten/lcv-rest-api/lcv-restapi-service.yaml
> ```
> 
> And when I am connecting to:
> `https://lima.ewi.tudelft.nl/lcv/APIEndpoints`
> I still got the old Endpoints page.
> 
> So I tried:
> 
> michelescarlato@monster:~$ `docker image ls`
> `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json: dial unix /var/run/docker.sock: connect: permission denied `
> 
> Thank you in advance for your support,
> Michele

I've added you to the Docker groups on the FASTEN servers. Run `groups` to see whether you're now part of `docker` group. And run the above Docker command again.
Let me know if you have issues.

**Comment by michelescarlato** [comment]
Thanks for the quick reply, @mir-am  .

I am noticing that on Monster, I cannot see the docker image. 
It could be in Lima?
Eventually, do I have access there?

**Comment by michelescarlato** [comment]
I could see some details of the pod that is running the docker image lcv-fasten-restapi:

```
michelescarlato@monster:~$ kubectl -n fasten describe pod lcv-fasten-restapi-7d4cf7bf49-v88lp
Name:         lcv-fasten-restapi-7d4cf7bf49-v88lp
Namespace:    fasten
Priority:     0
Node:         tehran/172.16.45.113
Start Time:   Wed, 14 Jul 2021 07:04:02 +0200
Labels:       app=lcv-fasten-restapi
              pod-template-hash=7d4cf7bf49
Annotations:  cni.projectcalico.org/podIP: 192.168.60.130/32
              cni.projectcalico.org/podIPs: 192.168.60.130/32
Status:       Running
IP:           192.168.60.130
IPs:
  IP:           192.168.60.130
Controlled By:  ReplicaSet/lcv-fasten-restapi-7d4cf7bf49
Containers:
  lcv-fasten-restapi:
    Container ID:   docker://0bf7cbc59cbe1773eaa96662effb70a384bdec8eae7f619fd0d2636310176f45
    Image:          docker.pkg.github.com/fasten-project/lcv-cm/fasten.lcv.plugin:latest
    Image ID:       docker-pullable://docker.pkg.github.com/fasten-project/lcv-cm/fasten.lcv.plugin@sha256:f801ce9f61e2d944004695d8634b42aa870e5465bbdb36f14bb6718c73bc1683
    Port:           3251/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 14 Jul 2021 07:04:06 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      memory:     4Gi
    Environment:  <none>
    Mounts:
      /mnt/fasten from fasten-mnt (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4rwpm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  fasten-mnt:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/fasten
    HostPathType:  Directory
  default-token-4rwpm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-4rwpm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```

But I cannot find the image on Monster. As far I could see [here](https://github.com/fasten-project/LCV-CM/runs/3063692222?check_suite_focus=true) the last image has been created.

**Comment by michelescarlato** [comment]
@mir-am  I fixed it.
Now the new version is deployed (still is missing a screenshot showing Postman usage of the lcv rest API).

I am going to close this issue.
